build_image:
  image: docker
  services:
    - docker:dind
  script:
    - docker version
    - docker info
    # build only when tagged
    - "[[ -z $CI_BUILD_TAG ]] && exit 0"
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
    - docker login registry.gitlab.com -u gitlab+deploy-token-215945 -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
